
services:

  server:
    build: .
    volumes:
      - source:/projeto
    command: /bin/bash
    tty: true
    environment:
      - DISPLAY=172.17.0.1${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:/root/.Xauthority
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev:/dev
      - source:/projeto
  
  client:
    build: .
    volumes:
      - source:/projeto
    command: /bin/bash
    tty: true

volumes:
  source:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/michel/Documents/GitHub/energy-ros2-cpp-python/