name: C++ SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SonarQube scanner
        uses: sonarsource/sonarcloud-github-action@v1

      - name: Run SonarQube analysis
        run: |
          sonar-scanner
